
structure         /path/xdna_most_WI.psf
coordinates       /path/xdna_most_WI.pdb 

outputName         xdna_most_equil1
binaryoutput       yes

bincoordinates     xdna_most_min.restart.coor

set firsttime      0
firsttimestep $firsttime
set temperature 300
temperature $temperature

cellBasisVector1 220 0 0           # Basis vector for cell (x2 - x1)
cellBasisVector2 0 80 0           # Basis vector for cell (y2 - y1)
cellBasisVector3 0 0 80          # Basis vector for cell (z2 - z1)
cellOrigin       -0.1135 0.0364 0.0273  # Center of cell



langevin on
langevinDamping     0.5 ;# damping coefficient (gamma); let's try 0.5 /ps
langevinTemp        $temperature
langevinHydrogen    off    ;# don't couple langevin bath to hydrogens

# Input

paraTypeCharmm      on
parameters          /path/par_all36_na.prm
parameters          /path/toppar_water_ions.mod.str

# Force-Field Parameters
exclude             scaled1-4
1-4scaling          1.0
switching           on
switchdist           8
cutoff              10
pairlistdist        12


# Integrator Parameters
timestep            2  ;# 1fs/step
rigidBonds          all  ;# needed for 2fs steps
nonbondedFreq       1
fullElectFrequency  3
stepspercycle       12

#PME (for full-system periodic electrostatics)
if {1} {
PME                 yes
PMEGridSpacing      1.5
}
xstFreq             1200
outputEnergies      1200
dcdfreq             1200
restartfreq         1200
outputPressure      1200
outputTiming        1200

#Constrained Atoms Constraint (set PDB beta-column to 1)
if {1} {
constraints       on
consref           xdna_most_WIbeta.pdb
conskfile         xdna_most_WIbeta.pdb
conskcol          B
}

run     24000
