# NAMD Configuration file for minimization and equilibration of a DNA molecule

# Input
structure         /path/xdna_most_WI.psf
coordinates       /path/xdna_most_WI.pdb

# Force field parameters
paraTypeCharmm      on
parameters          /path/par_all36_na.prm
parameters          /path/toppar_water_ions.mod.str

# Output
outputName        xdna_most_min              # Base name for output files
binaryoutput      yes                 # Write binary output files

xstFreq 	  1200
dcdfreq           1200                # Frequency for DCD output
outputEnergies    1200                 # Frequency for energy output
outputTiming      1200                 # Frequency for timing information
restartfreq	  1200

# Integration
timestep          2.0                 # Time step in fs ####2.0
rigidBonds        all                 # Rigid bonds involving hydrogen
nonbondedFreq     1                   # Frequency for nonbonded evaluation
fullElectFrequency 3                  # Frequency for full electrostatics
stepspercycle     12                  # Steps per cycle

# Periodic boundary conditions

cellBasisVector1 220 0 0           # Basis vector for cell (x2 - x1)
cellBasisVector2 0 80 0           # Basis vector for cell (y2 - y1)
cellBasisVector3 0 0 80          # Basis vector for cell (z2 - z1)
cellOrigin       -0.1135 0.0364 0.0273  # Center of cell



# Force-field settings
exclude           scaled1-4           # Exclude scaled 1-4 interactions
1-4scaling        1.0                 # Scaling for 1-4 interactions
switching         on                  # Use switching function
switchdist        8.0                # Distance for switching function
cutoff            10.0                # Nonbonded cutoff
pairlistdist      12.0                # Distance for pairlist
margin            15.0

# Temperature control
temperature       300                 # Temperature in K

# Constant Temperature Control

langevin on
langevinDamping 0.5
langevinTemp 300 
langevinHydrogen off

minimize 4800


