structure         /path/xdna_most_WI.psf
coordinates       /path/xdna_most_WI.pdb

outputName         xdna_tleast_prod
binaryoutput       yes

bincoordinates     xdna_most_equil2.restart.coor
binvelocities      xdna_most_equil2.restart.vel
extendedSystem     xdna_most_equil2.restart.xsc

set firsttime      0
firsttimestep $firsttime
set temperature 300


langevin on
langevinDamping     0.5 ;# damping coefficient (gamma); let's try 0.5 /ps
langevinTemp        $temperature
langevinHydrogen    off    ;# don't couple langevin bath to hydrogens

# Input

paraTypeCharmm      on
parameters          /path/par_all36_na.prm
parameters          /path/toppar_water_ions.mod.str

# Force-Field Parameters
exclude             scaled1-4
1-4scaling          1.0
switching           on
switchdist           8
cutoff              10
pairlistdist        12


# Integrator Parameters
timestep            2  ;# 1fs/step
rigidBonds          all  ;# needed for 2fs steps
nonbondedFreq       1
fullElectFrequency  3
stepspercycle       12

#PME (for full-system periodic electrostatics)
if {1} {
PME                 yes
PMEGridSpacing      1.5
}

# perform constant pressure simulation
if {1} {
langevinPiston        on      ;# turn this off for constant volume sim
langevinPistonTarget  1.01325 ;#  in bar -> 1 atm
langevinPistonPeriod  100
langevinPistonDecay   50
langevinPistonTemp    $temperature
}


xstFreq             4800
outputEnergies      4800
dcdfreq             4800
restartfreq         4800
outputPressure      4800
outputTiming        4800

#Constrained Atoms Constraint (set PDB beta-column to 1)
if {0} {
constraints       on
consref           /path/xdna_most_WIbeta.pdb
conskfile         /path/xdna_most_WIbeta.pdb
conskcol          B
}

if {1} {
extraBonds on
extraBondsFile /path/extrabonds_most.txt
}

run    48000000
